### PR TITLE
[Task 4] Integrate services with RDS

### PR DESCRIPTION
**Pull request by JulianRojasBet**
### What was done?

- [x] Task 4.1 is implemented
- [x] Task 4.2 is implemented
- [x] Task 4.3 is implemented
- [x] Your own Frontend application is integrated with Product Service (/products API) and products from Product Service are represented on Frontend
- [x] POST `/products` lambda functions returns error 400 status code if product data is invalid
- [x] All lambdas return error 500 status code on any error 
- [x] All lambdas do console.log for each incoming requests and their arguments
- [x] Transaction based creation of product. [See sql library docs for transactions.](https://www.npmjs.com/package/postgres#transactions)

**Score: 8/9**

> **Note:**
> The [pg](https://www.npmjs.com/package/pg) library was recommended to make the queries to RDS but as I have a lot of issues working with it and webpack y decide to use [postgres](https://www.npmjs.com/package/postgres) library instead

Links:
- [Front-end PR](https://github.com/JulianRojasBet/shop-react-redux-cloudfront/pull/3)
- [Front-end application](https://d19bm5j4q5aybe.cloudfront.net)
- [getProductsList](https://g2wfa1y430.execute-api.us-east-1.amazonaws.com/products)
- [createProduct](https://g2wfa1y430.execute-api.us-east-1.amazonaws.com/products)
- [getProductsById](https://g2wfa1y430.execute-api.us-east-1.amazonaws.com/products/3a88eec1-3d43-4225-8111-b38a87c78908)

### CODE REVIEW

**Comment by st3venrose** [comment]
I get "Internal server error" for creating a new product.
I used this data in the request body:

```json
{
    "title": "Product 2",
    "description": "Description 2",
    "price": 200,
    "count": 20
}
```

Am I missing something? Could you provide a working request body for that request?

Regarding the frontend integration, the FE app doesn't work. https://d19bm5j4q5aybe.cloudfront.net/

**Comment by JulianRojasBet** [comment]
Hi @st3venrose.

> I get "Internal server error" for creating a new product. I used this data in the request body:
> 
> ```json
> {
>     "title": "Product 2",
>     "description": "Description 2",
>     "price": 200,
>     "count": 20
> }
> ```
> 
> Am I missing something? Could you provide a working request body for that request?

You are getting "Internal server error" by the same reason as Front-end app is not working, even that this is an invalid body as `id` field is required, it should be a valid `uuid`. e.g. `bc957f3b-8d45-4923-96e5-2153f8d30883`. Also the json object should be like:

```json
{
    "id": "bc957f3b-8d45-4923-96e5-2153f8d30883"
    "title": "Product 2",
    "description": "Description 2",
    "price": 200,
    "count": 20
}
```

> Regarding the frontend integration, the FE app doesn't work. https://d19bm5j4q5aybe.cloudfront.net/

Sorry about that, as you can see in my [last commit](https://github.com/JulianRojasBet/shop-services-lambda/pull/2/commits/135188f7e50b9294d50e3b3389289f042c57fdb2), the issue happened because I was closing the DB connection after the first request. It should work now.

---

Thanks for reaching me and report me this issues.

**Comment by st3venrose** [comment]
FE works now. Creating a new product API response is:
```json
{
    "error": "Bad request"
}
```

I generated a new uuid4 and I used POST request with this request body:
```json
{
    "id": "cd25a9ee-9ec5-4b50-b442-be1a86f9a2c1",
    "title": "Product 2",
    "description": "Description 2",
    "price": 200,
    "count": 20
}
```

Actually, your DB should generate uuid, so it isn't a required property. Frontend app doesn't send uuid to the server. You can see on the admin site where new products can be created (https://d19bm5j4q5aybe.cloudfront.net/admin/products - creating product FE integration is not needed now, just try it and check what kind of data are in the request body when you submit).

**Comment by JulianRojasBet** [comment]
Yep, I realize that after I posted the comment. `createProduct` service is expecting the product object inside of a "body" attribute in the `event` object [as you can see here](https://github.com/JulianRojasBet/shop-services-lambda/blob/2f4e2e443df2977eb2361e904d1b6424840dc0db/product-service/functions/createProduct/handler.ts#L7). 

I changed the `createProduct` param type and instead destructure the `event` object, that way will work with the JSON you are expecting to work. Also I made `id` not a required attribute. [Here are the changes](https://github.com/JulianRojasBet/shop-services-lambda/pull/2/commits/68ae7930e10eaa23c3546ae12c84a7ed1a2bb321)

Sorry for all the confusion and thanks for your feedback.

**Comment by JulianRojasBet** [comment]
Well, I just discovered that the `createProduct` service is not working through the REST API, I was testing it through the serverless CLI using the `invoke` command and it worked as I expected. The issue is because `event.body` is base64 encoded.

**Comment by st3venrose** [comment]
> Well, I just discovered that the `createProduct` service is not working through the REST API, I was testing it through the serverless CLI using the `invoke` command and it worked as I expected. The issue is because `event.body` is base64 encoded.

`body` object is automatically added to the `event`, you shouldn't send it in your request. Add `content-type: application/json` header to your HTTP request and you will get json in your lambda so you don't have to use JSON.parse().

"event.body is base64 encoded" - I don't know why it's encoded, it shouldn't be. Try to check epam example app, maybe you can find something that can help you: https://github.com/EPAM-JS-Competency-center/shop-nodejs-aws-serverless/blob/main/product-service/serverless.yml

**Comment by JulianRojasBet** [comment]
> `body` object is automatically added to the `event`, you shouldn't send it in your request. Add `content-type: application/json` header to your HTTP request and you will get json in your lambda so you don't have to use JSON.parse().
> 
> "event.body is base64 encoded" - I don't know why it's encoded, it shouldn't be. Try to check epam example app, maybe you can find something that can help you: https://github.com/EPAM-JS-Competency-center/shop-nodejs-aws-serverless/blob/main/product-service/serverless.yml

Even using the `content-type` header I get a base64 body, hopefully I have already fixed it. I have read a little bit and it may be related with Lambda Proxy Integration. I will dig more into this for the next Task.

Thanks again for all your help. Please let me know if everything is working now for you.

**Comment by st3venrose** [comment]
If I set `Content-Type: application/json` then I get internal server error. POST endpoint works only without content type. It will be a problem when you have to integrate the POST endpoint with FE.
I could create a new product so I can give you points.

**Comment by JulianRojasBet** [comment]
I will dig into this issue further for next tasks. Thanks so much.

**Pull request merged**
